# Generated by Django 3.0.8 on 2020-07-15 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_posts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comments',
            field=models.ManyToManyField(related_name='postcomm', to=settings.AUTH_USER_MODEL),
        ),
    ]
